name: Sum Tables with Playwright

on:
  workflow_dispatch:

jobs:
  sum_tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install playwright

      - name: Download Playwright browsers
        run: npx playwright install

      - name: 24f2001127@ds.study.iitm.ac.in – Run sumTables script
        run: node sumTables.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

